### PR TITLE
Dependency injection for configuration refresh

### PR DESCRIPTION
**Pull request by abhilasharora**
This pull request contains the following changes for the .NET Core configuration provider.

1. Add an extension method to configure dependency injection for .NET Core applications
2. Enforce `AddAzureAppConfiguration` and `UseAzureAppConfiguration` pattern similar to `AddMvc` and `UseMvc` for ASP.NET Core applications that wish to use the activity-based middleware
3. Remove the AspNetCore-specific dependency to the package `Microsoft.AspNetCore.Http.Extensions` from the package `Microsoft.Extensions.Configuration.AzureAppConfiguration`
4. Simplify the code for activity-based middleware by using the global refresher instance injected using dependency injection to trigger refresh as a client and reduce coupling with the code for the provider
5. Add unit tests to validate the above scenarios

### CODE REVIEW

**Comment by zhenlan** [comment]
This PR includes breaking changes. I'd like to include this in the new v4 release too.

@abhilasharora can you please update when this PR is ready for review?

**Comment by abhilasharora** [comment]
> This PR includes breaking changes. I'd like to include this in the new v4 release too.
> 
> @abhilasharora can you please update when this PR is ready for review?

@zhenlan I revisited this PR and figured that the current approach doesn't work for ASP.NET Core 3.0. I had opened an issue https://github.com/dotnet/aspnetcore/issues/14400 for it in the past, so I'm currently looking into alternative ways to retrieve the data we need that works for both ASP.NET Core v2 and v3.

**Comment by zhenlan** [comment]
Okay. Do you like to close this PR and open a new one when you are ready?

**Comment by abhilasharora** [comment]
> Okay. Do you like to close this PR and open a new one when you are ready?

Sure

**Pull request closed without merging**
