### PR TITLE
Update provider version to 4.0.0-preview in AspNetCore package

### PR DESCRIPTION
**Pull request by abhilasharora**
This pull request updates the reference of the package `Microsoft.Extensions.Configuration.AzureAppConfiguration` to version `4.0.0-preview`.

### CODE REVIEW

**Comment by jimmyca15** [comment]
Just wanted to make sure. We're not doing a preview release of 4.0.0, we're just going straight to stable?

**Comment by abhilasharora** [comment]
> Just wanted to make sure. We're not doing a preview release of 4.0.0, we're just going straight to stable?

Yes, the stable version is needed to unblock the Speech Services Team.

**Comment by zhenlan** [comment]
I thought we were planning to release a preview first. When was the plan changed?

**Comment by abhilasharora** [comment]
> I thought we were planning to release a preview first. When was the plan changed?

The version upgrade to `4.0.0` stable was already done on June 18 as a part of pull request https://github.com/Azure/AppConfiguration-DotnetProvider/pull/174. This was done to ensure the Speech Services Team is unblocked. Let me know if you'd like me to exclude Refresher DI changes or JSON content type changes from this release.

**Comment by zhenlan** [comment]
We don't need to exclude any changes. We should do a v4 preview release first.

I see there is confusion about what the next release will be. We should start using milestones to track our releases. It helps to clarify what a release will be called and what will be included. I've created a [v4.0.0-preview](https://github.com/Azure/AppConfiguration-DotnetProvider/milestone/1) to get us started. Please assign issues that are addressed in upcoming release to it.

**Pull request merged**
